import type { MenuItem } from "./menu.types";

export function createMockMenuItems(): MenuItem[] {
  return [
    {
      id: "5b4ff458-7d90-4d20-a26f-9ca07ea30231",
      name: "Futomaki signature",
      description: "Riz vinaigré, avocat et finition sésame.",
      category: "main",
      price: 19,
      available: true,
      imageUrl: "/images/menu/futomaki.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: "9af7271a-a321-4236-a3bf-fcd4f61c88a6",
      name: "Maki saumon",
      description: "Saumon fondant et riz assaisonné minute.",
      category: "starter",
      price: 14,
      available: true,
      imageUrl: "/images/menu/maki-saumon.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: "f53b8b4b-1cc4-4f95-850d-91d6478f6d3a",
      name: "Plateau sushi maki sashimi",
      description: "Assortiment premium pour partage ou formule déjeuner.",
      category: "main",
      price: 32,
      available: true,
      imageUrl: "/images/menu/menu-sushi-maki-sashimi.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: "06b1b9d2-c2f8-4f92-b72f-e878035dbe33",
      name: "Rolls signature",
      description: "Sélection de rolls contemporains à forte rotation.",
      category: "main",
      price: 28,
      available: true,
      imageUrl: "/images/menu/menu-maki-roll.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: "7df66c25-fd5b-4c03-8b56-812d87bfda0d",
      name: "Sushi poulpe snacké",
      description: "Poulpe tendre, touche grillée et condiment citronné.",
      category: "starter",
      price: 17,
      available: true,
      imageUrl: "/images/menu/suchi-poulpe.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: "ab5a99af-e0d7-4a43-aaef-817594f3027e",
      name: "Nem croustillant",
      description: "Entrée croustillante servie avec herbes fraîches.",
      category: "starter",
      price: 12,
      available: true,
      imageUrl: "/images/starter/nem.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: "46c7b4ba-9f1e-4270-a1ad-ef12d048cf8a",
      name: "Glace vanille",
      description: "Dessert minute à la vanille, simple et efficace.",
      category: "dessert",
      price: 7,
      available: true,
      imageUrl: "/images/dessert/vanilla-ice-cream.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: "74f3dad8-3ea8-4f63-9d72-3f3932dd9a8d",
      name: "Bière artisanale",
      description: "Bière fraîche servie en bouteille ou en pression.",
      category: "drink",
      price: 8,
      available: true,
      imageUrl: "/images/drink/beer.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: "c8f41ba9-2da4-40e4-9e1a-2d2863842e8f",
      name: "Café serré",
      description: "Café court pour clôturer le repas.",
      category: "drink",
      price: 4,
      available: true,
      imageUrl: "/images/drink/cafee.png",
      createdAt: new Date().toISOString(),
    },
  ];
}
